# Generated by Django 5.0.4 on 2024-05-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometable',
            name='category',
        ),
    ]
