# Generated by Django 5.0.4 on 2024-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_hometable_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometable',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
