# Generated by Django 5.0.4 on 2024-05-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hometable_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometable',
            name='pricerange',
        ),
        migrations.AddField(
            model_name='hometable',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hometable',
            name='category',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hometable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hometable',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
