# Generated by Django 5.0.4 on 2024-06-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mailid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
