# Generated by Django 5.0.4 on 2024-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_product_id_listtable_fadvertisement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtable',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
