# Generated by Django 5.0.4 on 2024-06-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_listtable_fadvertisement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
