# Generated by Django 5.0.4 on 2024-06-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_hometable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometable',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
