# Generated by Django 5.0.6 on 2024-06-29 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_orderhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_history',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
